### ISSUE TITLE
Possible issue Doesn't install or run. Am I missing something crucial?

### ISSUE THREAD

**Issue by kjr247** [flexdec/mapit-MEAN-RESTful-app#1]
Kyle-3@KYLE-3-PC /C/Users/Kyle-3/Desktop/DEV/example
$ git clone https://github.com/felix-d/mapit-MEAN-RESTful-app.git
Cloning into 'mapit-MEAN-RESTful-app'...
remote: Counting objects: 1384, done.
remote: Compressing objects: 100% (1061/1061), done.
remote: Total 1384 (delta 215), reused 1384 (delta 215), pack-reused 0
Receiving objects: 100% (1384/1384), 2.66 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (215/215), done.
Checking connectivity... done.

Kyle-3@KYLE-3-PC /C/Users/Kyle-3/Desktop/DEV/example
$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path c:\Users\Kyle-3\Desktop\DEV\example\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058

npm ERR! package.json ENOENT, open 'c:\Users\Kyle-3\Desktop\DEV\example\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Kyle-3\Desktop\DEV\example\npm-debug.log
/c/Program Files/nodejs/npm: line 14:  4056 Signal 112              (core dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

Kyle-3@KYLE-3-PC /C/Users/Kyle-3/Desktop/DEV/example
$ npm install express body-parser mongoose passport passport-http bcrypt-nodejs -save
npm ERR! addLocal Could not install c:\Users\Kyle-3\Desktop\DEV\example-save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "express" "body-parser" "mongoose" "passport" "passport-http" "bcrypt-node
js" "-save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path c:\Users\Kyle-3\Desktop\DEV\example-save
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'c:\Users\Kyle-3\Desktop\DEV\example-save'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Kyle-3\Desktop\DEV\example\npm-debug.log
/c/Program Files/nodejs/npm: line 14:  6580 Signal 112              (core dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

Kyle-3@KYLE-3-PC /C/Users/Kyle-3/Desktop/DEV/example
$ node server.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\Users\Kyle-3\Desktop\DEV\example\server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by afhaque** [comment]
Are you sure that you have a package.json file? The errors you are getting typically come when npm doesnt see the package.json file that it uses to install packages.
