### ISSUE TITLE
mongoose dependency problems

### ISSUE THREAD

**Issue by arizona2014** [flexdec/mapit-MEAN-RESTful-app#4]
Even if I let  "mongoose": "^3.8.23" in the package.json as afhaque suggested in his  "Fixed initial loading of Map #3" pull commit,  I still got this ugly error : 

\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:246
        throw message;
        ^

TypeError: Cannot read property 'length' of undefined
    at processResults (..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31)
    at ..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
    at ..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
    at ..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
    at Server.Base._callHandler (..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:448:41)
    at ..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
    at MongoReply.parseBody (..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.<anonymous> (..\MEAN_REST_app\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:439:20)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)

**Comment by arizona2014** [comment]
To solve the problem you should use  "mongoose": "4.0.0" in the package.json
